export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const POST_POSTS_REQUEST = 'POST_POSTS_REQUEST';
export const PATCH_POSTS_REQUEST = 'PATCH_POSTS_REQUEST';
export const DELETE_POSTS_REQUEST = 'DELETE_POSTS_REQUEST';
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
