export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST"
// export const POST_MESSAGES_REQUEST = "POST_MESSAGES_REQUEST"
// export const PATCH_MESSAGES_REQUEST = "PATCH_MESSAGES_REQUEST"
// export const DELETE_MESSAGES_REQUEST = "DELETE_MESSAGES_REQUEST"