export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const POST_COMMENTS_REQUEST = 'POST_COMMENTS_REQUEST';
export const PATCH_COMMENTS_REQUEST = 'PATCH_COMMENTS_REQUEST';
export const DELETE_COMMENTS_REQUEST = 'DELETE_COMMENTS_REQUEST';
